### ISSUE TITLE
Consider depending on mysql driver RPM

### ISSUE THREAD

**Issue by fuero** [marhag87/atlassian-rpms#119]
As the mysql JDBC driver is in EL7, I'd suggest depending on it and using it rather than packaging the driver yourself.

From CentOS Linux release 7.4.1708 (Core):

```
Name        : mysql-connector-java
Epoch       : 1
Version     : 5.1.25
Release     : 3.el7
Repo        : base/7/x86_64
Summary     : Official JDBC driver for MySQL
URL         : http://dev.mysql.com/downloads/connector/j/
License     : GPLv2 with exceptions
```

**Comment by marhag87** [comment]
@fuero That would be great. 5.1.25 is a bit old though. Will it be updated?

**Comment by fuero** [comment]
RedHat's position is to version lock software to (OS) releases and provide / backport security fixes.

New feature releases are integrated in newer OS releases.

So updates to a package might be provided via EPEL or in a future EL release, or by third parties.

[Looking at Fedora](https://koji.fedoraproject.org/koji/buildinfo?buildID=1006151) which is "upstream" for EL, the current version of the driver it (Fedora 27) ships with is 2.1.2

Seems with the switch to MariaDB they renamed the package along the way to mariadb-java-client

**Comment by marhag87** [comment]
I'll go ahead and keep including it directly then. I need the newer version and this is far from an official package.
